spring:
  hateoas:
    use-hal-as-default-json-media-type: false
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
  data:
    rest:
      default-page-size: 10
      max-page-size: 500


storage:
  type: database
